// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ivan Chien",
            "email": "qyc027@gmail.com"
        },
        "license": {
            "name": "GPL-3.0 License",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "ping",
                "responses": {}
            }
        },
        "/problem/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "add a new problem",
                "parameters": [
                    {
                        "type": "string",
                        "description": "problem title",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "problem memory limitation",
                        "name": "memo_limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "problem time limitation",
                        "name": "time_limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "problem text",
                        "name": "text",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/problem/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "delete a problem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "problem memory limitation",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/problem/fetch": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "fetch an existed problem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "problem id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/problem/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list problems",
                "responses": {}
            }
        },
        "/problem/submit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "submit code",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "problem id",
                        "name": "problem_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "submission source code",
                        "name": "source_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "c",
                            "cpp",
                            "rust",
                            "python"
                        ],
                        "type": "string",
                        "description": "submission language",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/problem/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "update a problem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "problem id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "problem title",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "problem memory limitation",
                        "name": "memo_limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "problem time limitation",
                        "name": "time_limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "problem text",
                        "name": "text",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/submission/fetch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "submit code",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "submission id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/submission/rejudge": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "rejudge submission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "submission id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/fetch": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "fetch user info",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/logout": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "current user logout",
                "responses": {}
            }
        },
        "/user/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "fetch user info",
                "responses": {}
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nickname",
                        "name": "nickname",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "username",
                        "name": "user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "confirmation password",
                        "name": "password_confirm",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CoffeeOJ RUSTful APIs",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
